# Generated by Django 5.1.2 on 2024-10-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemdis', models.CharField(max_length=50)),
                ('itemname', models.CharField(max_length=50)),
                ('itemid', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
